import os
print("\n\n\033[32m [+] Installing Requirements...\033[0m")
print()
os.system("pip install --upgrade pip")
os.system("pkg upgrade && pkg update") 
os.system("pkg install python -y ")
os.system("pkg install python2 -y") 
os.system("pip install tabulate")
print()
print()
print("\n\n\033[32m [+] Now Run :- \033[34mpython Amazing-buttons.py \033[0m")
